/********************************************************************
 * engine.js
 ********************************************************************/
import { diffMinutes } from "./time.js";
export function computeTotalMinutes(interventions){let total=0; for(const it of interventions){total+=diffMinutes(it.start,it.end);} return total;}
export function computeBest11hWindow(interventions, period){const D=11*60; if(interventions.length===0){return {start:period.start, end:new Date(period.start.getTime()+D), minutes:0};} const points=new Set(); points.add(period.start.getTime()); points.add(period.end.getTime()); for(const it of interventions){points.add(it.start.getTime()); points.add(it.end.getTime()); points.add(it.start.getTime()-D); points.add(it.end.getTime()-D);} let best={start:period.start, end:new Date(period.start.getTime()+D), minutes:Infinity}; for(const t of points){const ws=new Date(t); const we=new Date(t+D); if(ws.getTime()<period.start.getTime()) continue; if(we.getTime()>period.end.getTime()) continue; let overlap=0; for(const it of interventions){const is=it.start.getTime(); const ie=it.end.getTime(); const s=Math.max(is,ws.getTime()); const e=Math.min(ie,we.getTime()); if(e> s) overlap+=(e-s)/60000;} if(overlap<best.minutes){best={start:ws,end:we,minutes:overlap};}} return best;}
export function computeRecuperation089(bestWindowMinutes){const h=bestWindowMinutes/60; if(h<6){return {type:"normal", heures:h, text:`${h.toFixed(2)} h (OK)`};} return {type:"repos", heures:h, text:`Journée de repos (${h.toFixed(2)} h > 6 h)`};}
export function buildSynthese(interventions, period){const totalMin=computeTotalMinutes(interventions); const totalH=totalMin/60; const best=computeBest11hWindow(interventions, period); const recup=computeRecuperation089(best.minutes); return {totalMinutes:totalMin, totalHeures:totalH, bestWindow:best, recup089:recup};}
export function formatSyntheseText(s){const tHM=`${s.totalHeures.toFixed(2)} h`; const wStart=s.bestWindow.start.toLocaleString(); const wEnd=s.bestWindow.end.toLocaleString(); const wMin=`${(s.bestWindow.minutes/60).toFixed(2)} h`; return `\nTotal interventions : ${tHM}\nFenêtre 11h       : ${wStart} → ${wEnd}\nDurée interventions dans fenêtre : ${wMin}\nRécup 089 : ${s.recup089.text}\n`;}
